# Open Music Theory Remix
# OER Music text book, remixed by drbutterfield
# a fork of Kris Shaffer, Bryn Hughes, and Brian Moseley, Open Music Theory, Hybrid Pedagogy 2014+. 
# http://openmusictheory.com/
# https://github.com/openmusictheory/openmusictheory.github.io
# http://www.hybridpedagogy.org/#publishing

# jekyll theme partly based on Lanyon, https://github.com/poole/lanyon

# site info
title: Inquiry-Based Music Theory
tagline: OER Text Book
description: "an open, interactive, online textbook for college music theory"
keywords: music theory, OER, university of idaho
owner: Sean Butterfield
email: sbutterfield@uidaho.edu
published: 2017
github-repo: https://github.com/drbutterfield/theory-draft-1

# urls
url: https://drbutterfield.github.io/theory-draft-1/
# baseurl: '/theory-draft-1'
baseurl: ''

# collections
collections:
  01-pitches-clefs-int:
    output: true
  02-scales-keys-triads-7chords:
    output: true
  03-intro-rhythm:
    output: true
  04-counterpoint-part1:
    output: true
  05-counterpoint-part2:
    output: true
  06-intro-harmonic:
    output: true
  07-harmonic-functions:
    output: true
  08-overtones:
    output: true
  09-partwriting-root-first:
    output: true
  10-partwriting-second-7chords:
    output: true
  11-ncts-embellishments:
    output: true
  12-phrasing-texture:
    output: true
  13-sequences-voiceleading-exceptions:
    output: true
  14-inst-ranges-trans-score-reduction:
    output: true

# ignore stuff
exclude: [oldOMTfiles]
